import type { TuiCallbackManifestRow } from "../tuiCallbackAudit";

const callbackNames = [
	"log",
	"beginCommand",
	"endCommand",
	"recordStatusActivityResult",
	"syncConfigSessionState",
	"saveConfigWorkspaceAdjustment",
	"submitConfigTextCommand",
	"applyNextConfigPolicyPreset",
	"openConfigResetConfirmation",
	"submitConfigResetCommand",
	"previewFile",
	"loadFiles",
	"refreshFiles",
	"disconnectRemoteFiles",
	"openSelectedFileEntry",
	"goToParentDirectory",
	"jumpToLocation",
	"jumpToNextLocation",
	"submitPathCommand",
	"submitRouteDestinationCommand",
	"submitRouteFilterCommand",
	"runToolPlan",
	"submitToolCommand",
	"applyToolPromptCommandLineInput",
	"submitEditorAppendLineCommand",
	"submitEditorInsertLineCommand",
	"submitEditorReplaceLineCommand",
	"undoEditorEdit",
	"deleteSelectedEditorLine",
	"submitEditorSaveConfirmationCommand",
	"submitToolHistoryFilterCommand",
	"submitToolHistoryCleanupCommand",
	"submitToolTargetLabelCommand",
	"submitToolTargetValueCommand",
	"submitToolTargetActionCommand",
	"submitToolTargetCleanupCommand",
	"submitToolTargetPresetCommand",
	"submitEndpointFilterCommand",
	"submitRouteFilterCleanupCommand",
	"submitEndpointFilterCleanupCommand",
	"submitPortProcessControlCommand",
	"openPalettePortProcessControlPreview",
	"submitTimelineSearchCommand",
	"submitTimelineSearchCleanupCommand",
	"submitLogSearchCommand",
	"submitLogsCleanupCommand",
	"submitControlConfirmationCommand",
	"runControlExecutionAttempt",
	"submitClipboardCommand",
	"goBackFileHistory",
	"goForwardFileHistory",
	"openSelectedFileOperation",
	"submitFileOperationDestinationCommand",
	"submitFileOperationConfirmCommand",
	"openClipboardConfirmation",
	"openSelectedUpdateHandoffClipboard",
	"openSelectedUpdateHandoffExternal",
	"submitExternalOpenCommand",
	"submitFileOpenCommand",
	"refreshHandoffIndex",
	"refreshAuditExportIndex",
	"refreshAuditExportArchiveIndex",
	"openSelectedHandoffFile",
	"openSelectedAuditExportFile",
	"openSelectedAuditExportArchiveFile",
	"openAuditArchiveRetentionPreview",
	"openInterfaceAuditArchiveRetentionPreview",
	"openSelectedAuditExportArchive",
	"openSelectedInterfaceEvidenceArchive",
	"openSelectedCleanupExportFile",
	"openSelectedToolExportFile",
	"openSelectedToolExportArchiveFile",
	"openSelectedStatusActivityToolsEvidenceSearchMatchFile",
	"openSelectedStatusActivityToolsEvidenceSearchMatchArchive",
	"openSelectedToolExportArchive",
	"openToolArchiveRetentionPreview",
	"cycleToolEvidenceFilter",
	"openToolEvidenceSearchPrompt",
	"submitToolEvidenceSearchCommand",
	"cycleInterfaceEvidenceStateFilter",
	"openInterfaceEvidenceSearchPrompt",
	"submitInterfaceEvidenceSearchCommand",
	"saveCurrentInterfaceEvidenceSearchPreset",
	"cycleInterfaceEvidenceSearchPreset",
	"openSelectedCleanupExportArchive",
	"archiveSelectedHandoffFile",
	"exportToolHistory",
	"exportRouteHandoff",
	"exportInterfaceSourceHandoff",
	"openInterfaceSourceHandoff",
	"openRouteHandoff",
	"exportEndpointHandoff",
	"openEndpointHandoff",
	"selectRemoteProfile",
	"submitRemoteProfileCommand",
	"submitRemoteConnectCommand",
	"cancelPendingRemoteConnect",
	"cancelOperationRun",
	"runSelectedOperationPreset",
	"submitRemoteHostKeyEvidenceInputCommand",
	"submitRemoteKnownHostsCandidateCommand",
	"submitRemoteKnownHostsPasteReviewCommand",
	"moveRemoteKnownHostsPasteReviewSelectionCommand",
	"selectRemoteKnownHostsPasteReviewCandidateCommand",
	"submitRemoteKnownHostsPasteSelectionCommand",
	"submitRemoteHostTrustReviewCommand",
	"inspectSelectedEndpointProcess",
	"openSelectedProcessFile",
	"refresh",
	"cycleStatusActivityResultHistoryFilter",
	"cycleStatusActivityResultTimelineJumpFilter",
	"getSelectedTimelineEvidenceTrailResultOptions",
	"selectNextTimelineEvidenceTrailExport",
	"cycleTimelineEvidenceTrailSourceFilter",
	"jumpSelectedTimelineEvidenceTrailSearch",
	"openSelectedTimelineEvidenceTrailExport",
	"getSelectedProcessControlEvidenceResultOptions",
	"selectNextProcessControlEvidenceExport",
	"jumpSelectedProcessControlEvidenceSearch",
	"openSelectedProcessControlEvidenceExport",
	"getSelectedRemoteKnownHostsSelectionEvidenceResultOptions",
	"selectNextRemoteKnownHostsSelectionEvidenceExport",
	"jumpSelectedRemoteKnownHostsSelectionEvidenceSearch",
	"openSelectedRemoteKnownHostsSelectionEvidenceExport",
	"openSelectedRemoteKnownHostsSelectionEvidenceClipboardHandoff",
	"exportSelectedRemoteKnownHostsSelectionEvidenceHandoff",
	"getSelectedInterfaceConfirmationEvidenceResultOptions",
	"selectNextInterfaceConfirmationEvidenceExport",
	"jumpSelectedInterfaceConfirmationEvidenceSearch",
	"openSelectedInterfaceConfirmationEvidenceExport",
	"selectNextStatusActivityResultTimelineJump",
	"selectNextRemoteKnownHostsEvidenceHandoff",
	"openSelectedRemoteKnownHostsEvidenceHandoff",
	"openSelectedStatusActivityResultTimelineJump",
	"runAction",
	"openCleanupHandoffPrompt",
	"dismissCleanupHandoff",
	"dismissConfigShelfLanding",
	"runConfigShelfFocusAction",
	"jumpToConfigManagedShelf",
	"reopenCleanupHandoffHistory",
	"refreshCleanupExportIndex",
	"refreshCleanupExportArchiveIndex",
	"refreshToolExportIndex",
	"refreshToolExportArchiveIndex",
	"submitCleanupExportArchiveCommand",
	"submitToolExportArchiveCommand",
	"submitAuditExportArchiveCommand",
	"submitAuditArchiveRetentionCommand",
	"submitToolArchiveRetentionCommand",
	"submitDnsServerProposalCommand",
	"openInterfaceStateProposal",
	"submitInterfaceConfirmationCommand",
	"exportCleanupHandoffHistory",
	"useInput",
] as const;

const wiringReasons = {
	log: "React setter/event publication",
	beginCommand: "React setter/event publication",
	endCommand: "React setter/event publication",
	refreshFiles: "direct I/O invocation",
	refresh: "direct I/O invocation",
} as const;

const delegatedCallbacks = {
	submitEditorAppendLineCommand: {
		owner: "src/tui/editorBuffer.ts",
		reason: "delegates editor append transition",
	},
	submitEditorInsertLineCommand: {
		owner: "src/tui/editorBuffer.ts",
		reason: "delegates editor insert transition",
	},
	submitEditorReplaceLineCommand: {
		owner: "src/tui/editorBuffer.ts",
		reason: "delegates editor replace transition",
	},
	undoEditorEdit: {
		owner: "src/tui/editorBuffer.ts",
		reason: "delegates editor undo transition",
	},
	deleteSelectedEditorLine: {
		owner: "src/tui/editorBuffer.ts",
		reason: "delegates editor delete transition",
	},
	applyToolPromptCommandLineInput: {
		owner: "src/tui/commandLine.ts",
		reason: "delegates typed tool prompt input transition",
	},
	submitToolTargetLabelCommand: {
		owner: "src/tui/toolHistory.ts",
		reason: "delegates selected-target label transition",
	},
	submitToolTargetValueCommand: {
		owner: "src/tui/toolHistory.ts",
		reason: "delegates selected-target value transition",
	},
	submitToolTargetActionCommand: {
		owner: "src/tui/toolHistory.ts",
		reason: "delegates selected-target action transition",
	},
	submitToolTargetCleanupCommand: {
		owner: "src/tui/toolHistory.ts",
		reason: "delegates selected-target cleanup transition",
	},
	submitToolTargetPresetCommand: {
		owner: "src/tui/toolHistory.ts",
		reason: "delegates selected-target save transition",
	},
} as const;

export const tuiCallbackManifest: TuiCallbackManifestRow[] = callbackNames.map(
	(name) => {
		const reason = wiringReasons[name as keyof typeof wiringReasons];
		const delegated =
			delegatedCallbacks[name as keyof typeof delegatedCallbacks];
		if (delegated) {
			return {
				name,
				owner: delegated.owner,
				classification: "delegated",
				slice:
					name.startsWith("submitEditor") ||
					name === "undoEditorEdit" ||
					name === "deleteSelectedEditorLine"
						? "editor-transitions"
						: "tool-target-transitions",
				reason: delegated.reason,
			};
		}
		return reason
			? {
					name,
					owner: "src/tui/App.tsx",
					classification: "wiring",
					slice: "baseline",
					reason,
				}
			: {
					name,
					owner: "src/tui/App.tsx",
					classification: "inline-decision",
					slice: "baseline",
					reason: "pending state-transition extraction",
				};
	},
);
